function Stream(b,c){b instanceof Stream?(this.enc=b.enc,this.pos=b.pos):(this.enc=b,this.pos=c)}Stream.prototype.get=function(b){void 0==b&&(b=this.pos++);if(b>=this.enc.length)throw"Requesting byte offset "+b+" on a stream of length "+this.enc.length;return this.enc[b]};Stream.prototype.hexDigits="0123456789ABCDEF";Stream.prototype.hexByte=function(b){return this.hexDigits.charAt(b>>4&15)+this.hexDigits.charAt(b&15)};
Stream.prototype.hexDump=function(b,c){for(var a="",d=b;d<c;++d)switch(a+=this.hexByte(this.get(d)),d&15){case 7:a+="  ";break;case 15:a+="\n";break;default:a+=" "}return a};Stream.prototype.parseStringISO=function(b,c){for(var a="",d=b;d<c;++d)a+=String.fromCharCode(this.get(d));return a};
Stream.prototype.parseStringUTF=function(b,c){for(var a="",d=0,e=b;e<c;)d=this.get(e++),a=128>d?a+String.fromCharCode(d):191<d&&224>d?a+String.fromCharCode((d&31)<<6|this.get(e++)&63):a+String.fromCharCode((d&15)<<12|(this.get(e++)&63)<<6|this.get(e++)&63);return a};Stream.prototype.reTime=/^((?:1[89]|2\d)?\d\d)(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])([01]\d|2[0-3])(?:([0-5]\d)(?:([0-5]\d)(?:[.,](\d{1,3}))?)?)?(Z|[-+](?:[0]\d|1[0-2])([0-5]\d)?)?$/;
Stream.prototype.parseTime=function(b,c){var a=this.parseStringISO(b,c),d=this.reTime.exec(a);if(!d)return"Unrecognized time: "+a;a=d[1]+"-"+d[2]+"-"+d[3]+" "+d[4];d[5]&&(a+=":"+d[5],d[6]&&(a+=":"+d[6],d[7]&&(a+="."+d[7])));d[8]&&(a+=" UTC","Z"!=d[8]&&(a+=d[8],d[9]&&(a+=":"+d[9])));return a};Stream.prototype.parseInteger=function(b,c){var a=c-b;if(4<a){var a=a<<3,d=this.get(b);if(0==d)a-=8;else for(;128>d;)d<<=1,--a;return"("+a+" bit)"}a=0;for(d=b;d<c;++d)a=a<<8|this.get(d);return a};
Stream.prototype.parseBitString=function(b,c){var a=this.get(b),d=(c-b-1<<3)-a,e="("+d+" bit)";if(20>=d)for(var f=a,e=e+" ",a=c-1;a>b;--a){for(d=this.get(a);8>f;++f)e+=d>>f&1?"1":"0";f=0}return e};Stream.prototype.parseOctetString=function(b,c){var a=c-b,d="("+a+" byte) ";20<a&&(c=b+20);for(var e=b;e<c;++e)d+=this.hexByte(this.get(e));20<a&&(d+=String.fromCharCode(8230));return d};
Stream.prototype.parseOID=function(b,c){for(var a,d=0,e=0,f=b;f<c;++f){var g=this.get(f),d=d<<7|g&127,e=e+7;g&128||(a=void 0==a?parseInt(d/40)+"."+d%40:a+("."+(31<=e?"bigint":d)),d=e=0);a+=String.fromCharCode()}return a};function ASN1(b,c,a,d,e){this.stream=b;this.header=c;this.length=a;this.tag=d;this.sub=e}
ASN1.prototype.typeName=function(){if(void 0==this.tag)return"unknown";var b=this.tag&31;switch(this.tag>>6){case 0:switch(b){case 0:return"EOC";case 1:return"BOOLEAN";case 2:return"INTEGER";case 3:return"BIT_STRING";case 4:return"OCTET_STRING";case 5:return"NULL";case 6:return"OBJECT_IDENTIFIER";case 7:return"ObjectDescriptor";case 8:return"EXTERNAL";case 9:return"REAL";case 10:return"ENUMERATED";case 11:return"EMBEDDED_PDV";case 12:return"UTF8String";case 16:return"SEQUENCE";case 17:return"SET";
case 18:return"NumericString";case 19:return"PrintableString";case 20:return"TeletexString";case 21:return"VideotexString";case 22:return"IA5String";case 23:return"UTCTime";case 24:return"GeneralizedTime";case 25:return"GraphicString";case 26:return"VisibleString";case 27:return"GeneralString";case 28:return"UniversalString";case 30:return"BMPString";default:return"Universal_"+b.toString(16)}case 1:return"Application_"+b.toString(16);case 2:return"["+b+"]";case 3:return"Private_"+b.toString(16)}};
ASN1.prototype.content=function(){if(void 0==this.tag)return null;if(0!=this.tag>>6)return null==this.sub?null:"("+this.sub.length+")";var b=this.tag&31,c=this.posContent(),a=Math.abs(this.length);switch(b){case 1:return 0==this.stream.get(c)?"false":"true";case 2:return this.stream.parseInteger(c,c+a);case 3:return this.sub?"("+this.sub.length+" elem)":this.stream.parseBitString(c,c+a);case 4:return this.sub?"("+this.sub.length+" elem)":this.stream.parseOctetString(c,c+a);case 6:return this.stream.parseOID(c,
c+a);case 16:case 17:return"("+this.sub.length+" elem)";case 12:return this.stream.parseStringUTF(c,c+a);case 18:case 19:case 20:case 21:case 22:case 26:return this.stream.parseStringISO(c,c+a);case 23:case 24:return this.stream.parseTime(c,c+a)}return null};ASN1.prototype.toString=function(){return this.typeName()+"@"+this.stream.pos+"[header:"+this.header+",length:"+this.length+",sub:"+(null==this.sub?"null":this.sub.length)+"]"};
ASN1.prototype.toPrettyString=function(b){void 0==b&&(b="");var c=b+this.typeName()+" @"+this.stream.pos,c=c+("+"+this.header);0<=this.length&&(c+="+");c+=this.length;if(this.tag&32)c+=" (constructed)";else if((3==this.tag||4==this.tag)&&null!=this.sub)c+=" (encapsulates)";c+="\n";if(null!=this.sub){b+="  ";for(var a=0,d=this.sub.length;a<d;++a)c+=this.sub[a].toPrettyString(b)}return c};ASN1.prototype.posStart=function(){return this.stream.pos};
ASN1.prototype.posContent=function(){return this.stream.pos+this.header};ASN1.prototype.posEnd=function(){return this.stream.pos+this.header+Math.abs(this.length)};ASN1.prototype.fakeHover=function(b){this.node.className+=" hover";b&&(this.head.className+=" hover")};ASN1.prototype.fakeOut=function(b){var c=/ ?hover/;this.node.className=this.node.className.replace(c,"");b&&(this.head.className=this.head.className.replace(c,""))};
ASN1.prototype.toHexDOM_sub=function(b,c,a,d,e){if(!(d>=e)){var f=document.createElement("span");f.className=c;f.appendChild(document.createTextNode(a.hexDump(d,e)));b.appendChild(f)}};
ASN1.prototype.toHexDOM=function(b){var c=document.createElement("span");c.className="hex";void 0==b&&(b=c);this.head.hexNode=c;this.head.onmouseover=function(){this.hexNode.className="hexCurrent"};this.head.onmouseout=function(){this.hexNode.className="hex"};c.asn1=this;c.onmouseover=function(){var a=!b.selected;a&&(b.selected=this.asn1,this.className="hexCurrent");this.asn1.fakeHover(a)};c.onmouseout=function(){var a=b.selected==this.asn1;this.asn1.fakeOut(a);a&&(b.selected=null,this.className=
"hex")};this.toHexDOM_sub(c,"tag",this.stream,this.posStart(),this.posStart()+1);this.toHexDOM_sub(c,0<=this.length?"dlen":"ulen",this.stream,this.posStart()+1,this.posContent());if(null==this.sub)c.appendChild(document.createTextNode(this.stream.hexDump(this.posContent(),this.posEnd())));else if(0<this.sub.length){var a=this.sub[0],d=this.sub[this.sub.length-1];this.toHexDOM_sub(c,"intro",this.stream,this.posContent(),a.posStart());for(var a=0,e=this.sub.length;a<e;++a)c.appendChild(this.sub[a].toHexDOM(b));
this.toHexDOM_sub(c,"outro",this.stream,d.posEnd(),this.posEnd())}return c};ASN1.decodeLength=function(b){var c=b.get(),a=c&127;if(a==c)return a;if(3<a)throw"Length over 24 bits not supported at position "+(b.pos-1);if(0==a)return-1;for(var d=c=0;d<a;++d)c=c<<8|b.get();return c};ASN1.hasContent=function(b,c,a){if(b&32)return!0;if(3>b||4<b)return!1;var d=new Stream(a);3==b&&d.get();if(d.get()>>6&1)return!1;try{var e=ASN1.decodeLength(d);return d.pos-a.pos+e==c}catch(f){return!1}};
ASN1.decode=function(b){b instanceof Stream||(b=new Stream(b,0));var c=new Stream(b),a=b.get(),d=ASN1.decodeLength(b),e=b.pos-c.pos,f=null;if(ASN1.hasContent(a,d,b)){var g=b.pos;3==a&&b.get();f=[];if(0<=d){for(var h=g+d;b.pos<h;)f[f.length]=ASN1.decode(b);if(b.pos!=h)throw"Content size is not correct for container starting at offset "+g;}else try{for(;;){h=ASN1.decode(b);if(0==h.tag)break;f[f.length]=h}d=g-b.pos}catch(j){throw"Exception while decoding undefined length content: "+j;}}else b.pos+=d;
return new ASN1(c,e,d,a,f)};
